image_topic: "image_data"
waypoint_topic: "waypoint_topic"
img_width: 320
img_height: 240
pool_size: 256
rb_img_url: "tcp://*:9001"
rb_wp_url: "tcp://*:"
container_admin_name: "QBApp1"
server_admin_port: 9090
server_system_port: 9191
num_publishers: 2
