image_topic: "image_data"
waypoint_topic: "waypoint_topic"
img_width: 320
img_height: 240
pool_size: 256
rb_img_url: "tcp://localhost:9004"
rb_wp_url: "tcp://*:9005"
container_admin_name: "QBApp2"
server_admin_port: 9091
server_system_port: 9192