file_images_path: "/home/javi/projects/melissa/tests/data"
img_width: 320
img_height: 240
restart_if_no_more_images: true
robo_bee_prefix: 100000
img_cv_type: 16
image_topic: "image_data"
waypoint_topic: "waypoint_topic"
pool_size: 256
qb_img_url: "tcp://localhost:9001"
qb_wp_url: "tcp://localhost:9002"
container_admin_name: "RBApp1"
server_admin_port: 9292
server_system_port: 9393